"use client";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import { motion } from "framer-motion";
import { Inter, Silkscreen } from "next/font/google";
import localFont from "next/font/local";
import { usePathname } from "next/navigation";
import React from "react";
import { Mouse } from "./components/mouse";
import { Sidebar } from "./components/sidebar";
import "./globals.css";

const silkscreen = Silkscreen({ subsets: ["latin"], variable: "--font-silkscreen", weight: "400" });
const inter = Inter({ subsets: ["latin"] });
const grotesk = localFont({ src: "../../public/fonts/Grotesk.otf", variable: "--font-grotesk" });

export const metadata = {
  title: "Ploeg",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [position, setPosition] = React.useState({
    x: window?.innerWidth / 2,
    y: 0,
  });

  const handleMouseMove = (event: React.MouseEvent) => {
    const { clientX, clientY } = event;
    setPosition({ x: clientX, y: clientY });
  };

  const pathname = usePathname();

  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en" className="overflow-hidden">
        <body className={`${inter.className} ${silkscreen.variable}`} suppressHydrationWarning>
          <main className="m-10">
            <div className="border-2 rounded-xl">
              <div className="">
                <div className="m-8 min-h-[calc(100vh-148px)] " onMouseMove={handleMouseMove}>
                  {pathname !== "/" && (
                    <motion.div onMouseMove={handleMouseMove}>
                      <Mouse r={1.5} x={position.x} y={position.y} blur={false} />
                    </motion.div>
                  )}

                  <div className="grid lg:grid-cols-5">
                    <Sidebar className="col-span-1" />
                    <div className={cn(pathname === "/" ? "col-span-5" : "col-span-4")}>
                      {children}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </main>
          <Toaster />
        </body>
      </html>
    </QueryClientProvider>
  );
}
