#pragma warning disable // Disable all warnings
using Newtonsoft.Json;

namespace OCPP.Protocol.NotifyReportResponse;

/// <summary>
/// This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
/// </summary>
public class CustomDataType
{
  [JsonProperty("vendorId", NullValueHandling = NullValueHandling.Ignore)]
  public string VendorId { get; set; }

  /// <summary>
  /// This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
  /// </summary>
  public object this[string k] { get => () => { }; set { } }
}

/// <summary>
/// This file was automatically generated by json-schema-to-typescript.
/// DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
/// and run json-schema-to-typescript to regenerate this file.
/// </summary>
public class NotifyReportResponse
{
  [JsonProperty("customData", NullValueHandling = NullValueHandling.Ignore)]
  public CustomDataType? CustomData { get; set; }
}